name: Release Maker

on:
  push:
    branches: ["main"]

jobs:
  release_maker:
    runs-on: ubuntu-latest
    steps:
      - name: Release Maker
        uses: kbrashears5/github-action-release-maker@v1.0.3
        with:
          VERSION: "0.1.1"
          TOKEN: ${{ secrets.ACTIONS }}
